[phases.setup]
nixPkgs = [
    'python311',
    'python311Packages.pip',
    'ffmpeg',
    'fontconfig',
    'liberation_ttf',
    'imagemagick',
    'corefonts',
    'dejavu_fonts',
    'noto-fonts'
]


[phases.build]
cmds = [
    "mkdir -p /root/.config/fontconfig",
    "echo '<?xml version=\"1.0\"?><fontconfig><dir>/nix/var/nix/profiles/default/lib/X11/fonts</dir><dir>/nix/var/nix/profiles/default/share/fonts</dir><cachedir>/tmp/fontconfig</cachedir></fontconfig>' > /root/.config/fontconfig/fonts.conf"
]


