[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'ffmpeg']

[phases.install]
cmds = [
  "pip3 install --no-cache-dir --upgrade pip",
  "pip3 install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "python3 -m pip install --no-cache-dir --upgrade pip",
  "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python3 main.py" 